services:
  server:
    image: server:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "9999:9999"
    environment:
      - ASPNETCORE_URLS=http://+:9999
    deploy:
      replicas: 1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge